require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/RedundantFetchBlock:
  Enabled: false
